apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  selector:
    app: redis-deployment
  type: ClusterIP
  ports:
  - name: vote-deployment
    port: 6379
    targetPort: 6379